name: Build ZMK firmware
on:
  push:
    branches-ignore:
      - EnableBluetooth
  pull_request:
    branches-ignore:
      - EnableBluetooth
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
